// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: attendance_queries.sql

package repository

import (
	"context"
	"time"
)

const saveEmployeeAttendance = `-- name: SaveEmployeeAttendance :exec
INSERT INTO attendance (employee_id, timestamp, type, created_by, updated_by)
VALUES ((
			select id
			from employee
			where username = $1
			),
		$2,
		$3,
		$4,
		$5)
`

type SaveEmployeeAttendanceParams struct {
	Username  string         `db:"username"`
	Timestamp time.Time      `db:"timestamp"`
	Type      AttendanceType `db:"type"`
	CreatedBy string         `db:"created_by"`
	UpdatedBy string         `db:"updated_by"`
}

func (q *Queries) SaveEmployeeAttendance(ctx context.Context, arg *SaveEmployeeAttendanceParams) error {
	_, err := q.db.Exec(ctx, saveEmployeeAttendance,
		arg.Username,
		arg.Timestamp,
		arg.Type,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	return err
}
