// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"context"
)

type Querier interface {
	FindEmployeeByID(ctx context.Context, id int32) (*Employee, error)
	FindEmployeeByUsername(ctx context.Context, username string) (*Employee, error)
	InsertEmployee(ctx context.Context, arg *InsertEmployeeParams) error
	InsertEmployeeRole(ctx context.Context, arg *InsertEmployeeRoleParams) error
	SaveEmployeeAttendance(ctx context.Context, arg *SaveEmployeeAttendanceParams) error
}

var _ Querier = (*Queries)(nil)
