// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"payroll/internal/infrastructure/config"
	"payroll/internal/infrastructure/log"
	"payroll/internal/presentation/router"
	"payroll/internal/presentation/server"
)

// Injectors from wire.go:

func NewWebServer() (*WebServer, error) {
	configConfig, err := config.LoadConfig()
	if err != nil {
		return nil, err
	}
	serverConfig := configConfig.Server
	logger := log.SetDefaultLogger(configConfig)
	chiRouter := router.NewRouter(configConfig, logger)
	httpServer := server.NewServer(serverConfig, chiRouter)
	webServer := &WebServer{
		cfg: configConfig,
		srv: httpServer,
	}
	return webServer, nil
}
