// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"payroll/internal/app"
	"payroll/internal/app/attendance/service"
	"payroll/internal/app/auth/dto"
	"payroll/internal/app/auth/repository"
	service2 "payroll/internal/app/auth/service"
	"payroll/internal/app/common/message"
	service3 "payroll/internal/app/payroll/service"
	"payroll/internal/infrastructure/config"
	"payroll/internal/infrastructure/database/postgres"
	"payroll/internal/infrastructure/log"
	"payroll/internal/infrastructure/messagebus"
	"payroll/internal/presentation"
	"payroll/internal/presentation/middleware"
	"payroll/internal/presentation/router"
	"payroll/internal/presentation/server"
	"payroll/pkg/jwt"
)

// Injectors from wire.go:

func NewWebServer() (*WebServer, error) {
	configConfig, err := config.LoadConfig()
	if err != nil {
		return nil, err
	}
	serverConfig := configConfig.Server
	logger := log.SetDefaultLogger(configConfig)
	authConfig := configConfig.Auth
	jwt := ProvideJWT(authConfig)
	jwtAuthMiddleware := middleware.WithJWTAuth(jwt)
	databaseConfig := configConfig.Database
	querier, err := postgres.Connect(databaseConfig)
	if err != nil {
		return nil, err
	}
	authRepository := repository.NewAuthRepository(querier)
	isAdminMiddleware := middleware.IsAdmin(authRepository)
	middlewares := &presentation.Middlewares{
		WithJWTAuth: jwtAuthMiddleware,
		IsAdmin:     isAdminMiddleware,
	}
	attendanceService := service.NewAttendanceService(querier)
	authService := service2.NewAuthService(authConfig, authRepository, jwt)
	kafkaConfig := configConfig.Kafka
	client, err := messagebus.NewKafkaClient(kafkaConfig)
	if err != nil {
		return nil, err
	}
	messagePublisher := message.NewMessagePublisher(kafkaConfig, client)
	payrollService := service3.NewPayrollService(messagePublisher)
	services := &app.Services{
		AttendanceService: attendanceService,
		AuthService:       authService,
		PayrollService:    payrollService,
	}
	chiRouter := router.NewRouter(configConfig, logger, middlewares, services)
	httpServer := server.NewServer(serverConfig, chiRouter)
	webServer := &WebServer{
		cfg:         configConfig,
		srv:         httpServer,
		kafkaClient: client,
	}
	return webServer, nil
}

// wire.go:

func ProvideJWT(cfg config.AuthConfig) jwt.JWT[*dto.JWTClaims] {
	return jwt.NewJWT[*dto.JWTClaims](jwt.Config{
		SecretKey: cfg.JWTSecret,
	})
}
