#!/bin/bash
# This script creates a new migration file in the database.

echo "Creating new migration file..."

source .env

filename=$1

go tool goose -dir ./internal/infrastructure/database/postgres/migration postgres "user=${POSTGRES_USER} password=${POSTGRES_PASSWORD} dbname=${POSTGRES_DB} host=${POSTGRES_HOST} port=${POSTGRES_PORT} sslmode=disable" create "$filename" sql